// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBROLja622D9rjMX0vXoESAWOoItoyz6aE',
    appId: '1:801351041908:web:758459eae00e14a4abe221',
    messagingSenderId: '801351041908',
    projectId: 'reddit-clone-40b4e',
    authDomain: 'reddit-clone-40b4e.firebaseapp.com',
    storageBucket: 'reddit-clone-40b4e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnT8GebshUmSlFeSOfKwSW7U8cjgB-89c',
    appId: '1:801351041908:android:11b5ee0d47870e2cabe221',
    messagingSenderId: '801351041908',
    projectId: 'reddit-clone-40b4e',
    storageBucket: 'reddit-clone-40b4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl_MRdUdDE_2hM5D6o7Bkwil17vQFcu8g',
    appId: '1:801351041908:ios:15d98eae563ef7dcabe221',
    messagingSenderId: '801351041908',
    projectId: 'reddit-clone-40b4e',
    storageBucket: 'reddit-clone-40b4e.appspot.com',
    iosClientId: '801351041908-160cjo0e5ka4g3ef3rbrum8sdai0h6si.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
